version: '3'
services:
  node:
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/infinity-scroll
      - /srv/infinity-scroll/node_modules
    working_dir: /srv/infinity-scroll
    command: 'yarn dev'